name: My First Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'The home drive on the machine'
        required: true
      logLevel:
        description: 'Log Level'
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tag:
        description: 'Apply tag after succesfull test run'
        required: true
        type: boolean
      environment:
        description: 'Environment to run tests against'
        required: false
        type: environment
        default: ''
  
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List all the files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
      - name: Workflow inputs
        run: |
          echo "Homedrive: ${{ inputs.homedrive }}"
          echo "Log level: ${{ inputs.logLevel }}"
          echo "Environment: ${{ inputs.environment }}"
        if: ${{ github.event_name == 'workflow_dispatch' }}

  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job: ${{ github.job }}"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: "echo Job: ${{ github.job }}"

  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: "echo Job: ${{ github.job }}"

  job_4:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]
    steps:
      - run: "echo Job: ${{ github.job }}"

  InstallDep:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm install
      - run: npm run build
      




    
